"""
india_clause_templates.py
--------------------------
Clause template library scoped to Indian contract law. Used by the
Drafting Wizard (Module 1) after the TF-IDF/SVM classifier selects a
clause category -- this module supplies the actual India-specific
template text and fills it with Jinja2.

Legal grounding (for your records / methodology section, not shown to
end users):
  - Governing law / jurisdiction defaults to an Indian state court and
    cites the Indian Contract Act, 1872 (the general law of contract)
    rather than a generic/US "state of Delaware" style clause.
  - Arbitration clause follows the Arbitration and Conciliation Act, 1996
    (as amended 2015/2019), the standard route Indian commercial
    contracts use to avoid civil court backlogs.
  - Stamp duty note reflects the Indian Stamp Act, 1899 and state-level
    stamp acts (duty varies by state -- flagged for the user to confirm
    rather than hard-coded, since e.g. Maharashtra/Karnataka/Delhi rates
    differ).
  - Company-party clauses reference the Companies Act, 2013 where
    relevant (e.g. authorised signatory language, common seal).
  - Confidentiality/IP clauses reference the Information Technology Act,
    2000 where data/electronic records are involved.

IMPORTANT: This is drafting assistance, not legal advice. Every
generated contract should carry the disclaimer in DISCLAIMER_TEXT and
be reviewed by a licensed Indian advocate before execution -- this
should be surfaced in the Streamlit UI, not just in code comments.
"""
from jinja2 import Template

DISCLAIMER_TEXT = (
    "This document has been generated by an automated drafting tool for "
    "informational purposes only and does not constitute legal advice. "
    "It should be reviewed by a licensed advocate registered with the "
    "Bar Council of India before execution, and stamped/registered as "
    "required under the applicable state Stamp Act and the Registration "
    "Act, 1908."
)

INDIAN_STATES_WITH_HIGH_COURTS = [
    "Maharashtra", "Delhi", "Karnataka", "Tamil Nadu", "West Bengal",
    "Telangana", "Gujarat", "Uttar Pradesh", "Rajasthan", "Kerala",
]

# ---------------------------------------------------------------------
# Governing Law / Jurisdiction (defaults to India; state is a parameter)
# ---------------------------------------------------------------------
GOVERNING_LAW_TEMPLATE = Template(
    "This Agreement shall be governed by and construed in accordance "
    "with the laws of India, including the Indian Contract Act, 1872. "
    "Subject to Clause on Dispute Resolution below, the courts at "
    "{{ city }}, {{ state }} shall have exclusive jurisdiction over any "
    "matter arising out of or in connection with this Agreement."
)

# ---------------------------------------------------------------------
# Dispute Resolution / Arbitration (Arbitration and Conciliation Act, 1996)
# ---------------------------------------------------------------------
ARBITRATION_TEMPLATE = Template(
    "Any dispute, controversy, or claim arising out of or relating to "
    "this Agreement, including its breach, termination, or validity, "
    "shall be referred to and finally resolved by arbitration under the "
    "Arbitration and Conciliation Act, 1996 (as amended). The arbitration "
    "shall be conducted by {{ num_arbitrators }} arbitrator(s), the seat "
    "of arbitration shall be {{ seat_city }}, India, and the proceedings "
    "shall be conducted in the {{ language }} language."
)

# ---------------------------------------------------------------------
# Stamp Duty & Execution note (Indian Stamp Act, 1899 + state acts)
# ---------------------------------------------------------------------
STAMP_DUTY_NOTE_TEMPLATE = Template(
    "This Agreement is executed in {{ state }} and is subject to stamp "
    "duty under the {{ state }} Stamp Act (or the Indian Stamp Act, 1899, "
    "where no state-specific enactment applies). The parties are advised "
    "to confirm the applicable stamp duty rate for this instrument type "
    "with a local stamp/registration authority prior to execution, as "
    "rates vary by state and are revised periodically."
)

# ---------------------------------------------------------------------
# Confidentiality (referencing IT Act, 2000 for electronic records)
# ---------------------------------------------------------------------
CONFIDENTIALITY_TEMPLATE = Template(
    "Each party shall keep confidential all non-public information "
    "disclosed by the other party in connection with this Agreement "
    "(\"Confidential Information\") and shall not disclose such "
    "information to any third party without prior written consent, "
    "except as required by law. Where Confidential Information is held "
    "or transmitted in electronic form, both parties shall comply with "
    "the applicable data protection and reasonable security practice "
    "requirements under the Information Technology Act, 2000 and rules "
    "made thereunder."
)

# ---------------------------------------------------------------------
# Termination
# ---------------------------------------------------------------------
TERMINATION_TEMPLATE = Template(
    "Either party may terminate this Agreement by providing "
    "{{ notice_days }} days' prior written notice to the other party. "
    "Either party may terminate this Agreement with immediate effect "
    "upon a material breach by the other party that remains uncured for "
    "{{ cure_days }} days after written notice of such breach."
)

# ---------------------------------------------------------------------
# Signatory block (Companies Act, 2013 authorised signatory language)
# ---------------------------------------------------------------------
SIGNATORY_BLOCK_TEMPLATE = Template(
    "For and on behalf of {{ party_name }}\n"
    "(a company incorporated under the Companies Act, 2013{{ cin_note }})\n"
    "Authorised Signatory: {{ signatory_name }}\n"
    "Designation: {{ designation }}"
)


def render_governing_law(city="Mumbai", state="Maharashtra"):
    return GOVERNING_LAW_TEMPLATE.render(city=city, state=state)


def render_arbitration(num_arbitrators=1, seat_city="Mumbai", language="English"):
    return ARBITRATION_TEMPLATE.render(
        num_arbitrators=num_arbitrators, seat_city=seat_city, language=language
    )


def render_stamp_duty_note(state="Maharashtra"):
    return STAMP_DUTY_NOTE_TEMPLATE.render(state=state)


def render_confidentiality():
    return CONFIDENTIALITY_TEMPLATE.render()


def render_termination(notice_days=30, cure_days=15):
    return TERMINATION_TEMPLATE.render(notice_days=notice_days, cure_days=cure_days)


def render_signatory_block(party_name, signatory_name, designation, cin=None):
    cin_note = f", CIN: {cin}" if cin else ""
    return SIGNATORY_BLOCK_TEMPLATE.render(
        party_name=party_name,
        signatory_name=signatory_name,
        designation=designation,
        cin_note=cin_note,
    )


# Maps clause categories (as predicted by clause_classifier.joblib, using
# CUAD's category names) to the India-specific renderer to use instead of
# a generic template. Categories not listed here fall back to the
# existing general template library unchanged.
INDIA_TEMPLATE_ROUTER = {
    "Governing Law": render_governing_law,
    "Dispute Resolution": render_arbitration,   # if you add this category
    "Confidentiality": render_confidentiality,
}


if __name__ == "__main__":
    # Quick manual smoke test
    print(render_governing_law(city="Pune", state="Maharashtra"))
    print()
    print(render_arbitration(seat_city="Bengaluru"))
    print()
    print(render_stamp_duty_note(state="Karnataka"))
    print()
    print(render_confidentiality())
    print()
    print(render_termination())
    print()
    print(render_signatory_block("Acme Technologies Pvt. Ltd.", "R. Sharma", "Director", cin="U72200MH2015PTC123456"))
