import streamlit as st
from services.pdf_reader import extract_text_from_pdf
from services.review_pipeline import run_review, format_report
from services.database_service import save_history_record
from utils.ui import load_css, page_header

st.set_page_config(
    page_title="Review Contract · AI Legal Assistant",
    page_icon="⚖️",
    layout="wide",
    initial_sidebar_state="expanded",
)

load_css()

page_header(
    "📄 Contract Review Workspace",
    "Upload or paste a contract to receive a structured, accurate clause-by-clause analysis under Indian law.",
)

# ─────────────────────────────────────────────────────────────────────────────
# Disclaimer banner
# ─────────────────────────────────────────────────────────────────────────────
st.info(
    "**Important:** This review is generated by a local hybrid ML analysis pipeline (TF-IDF/SVM clause "
    "classifier, CRF entity tagger, Random Forest risk model, handwritten risk rules, and India legal templates). "
    "It does not constitute legal advice and is not a substitute for review by a qualified legal advocate."
)

# ─────────────────────────────────────────────────────────────────────────────
# § 01 — Input
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="section-head"><span class="tag">§ 01</span><h2>Provide Contract</h2></div>
""", unsafe_allow_html=True)

tab_upload, tab_paste = st.tabs(["📄 Upload PDF / DOCX", "📝 Paste Contract Text"])

contract_text = ""
contract_name = "Contract"

with tab_upload:
    st.markdown('<div class="wizard-card">', unsafe_allow_html=True)
    uploaded_file = st.file_uploader(
        "Upload Agreement (PDF or DOCX)",
        type=["pdf", "docx"],
        help="Upload a legal contract file for structured review.",
    )
    st.markdown('</div>', unsafe_allow_html=True)

    if uploaded_file is not None:
        with st.spinner("Extracting text from document..."):
            contract_text = extract_text_from_pdf(uploaded_file)
        contract_name = uploaded_file.name
        if contract_text and len(contract_text.strip()) >= 50:
            st.markdown(
                f'<div class="status-pill"><span class="dot"></span> Loaded: '
                f'<strong>{uploaded_file.name}</strong> '
                f'({len(contract_text):,} characters)</div>',
                unsafe_allow_html=True,
            )
        else:
            st.warning(
                "Could not extract sufficient text from the uploaded file. "
                "Ensure the PDF is not a scanned image. You can also try pasting "
                "the contract text in the other tab."
            )
            contract_text = ""

with tab_paste:
    pasted = st.text_area(
        "Paste contract text here",
        height=320,
        placeholder="Paste the full contract text to review...",
    )
    if pasted.strip():
        contract_text = pasted.strip()
        contract_name = "Pasted Contract"

# ─────────────────────────────────────────────────────────────────────────────
# § 02 — Run Review
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<br>", unsafe_allow_html=True)

run_btn = st.button(
    "🔍 Run Contract Review",
    type="primary",
    use_container_width=True,
    disabled=(len(contract_text.strip()) < 50),
)

if len(contract_text.strip()) > 0 and len(contract_text.strip()) < 50:
    st.warning("Contract text is too short to analyse. Please provide more content.")

if run_btn:
    if not contract_text or len(contract_text.strip()) < 50:
        st.error("No contract text available for review. Please upload a file or paste text above.")
    else:
        with st.spinner("Running contract analysis pipeline (Classifier, CRF, Risk models, India rules)..."):
            result = run_review(contract_text)
            review_report = format_report(result, contract_name=contract_name)

        # Save to history
        save_history_record(
            contract_name=contract_name,
            contract_type=result.overview.contract_type_guess,
            activity_type="Reviewed",
            description=f"Contract review completed for {contract_name}.",
            result_content=review_report,
        )

        st.success("Review completed.")
        st.markdown("<br>", unsafe_allow_html=True)

        # ── § 03 — Report ────────────────────────────────────────────────────
        st.markdown("""
        <div class="section-head"><span class="tag">§ 02</span><h2>Review Report</h2></div>
        """, unsafe_allow_html=True)

        # ── Summary metrics ──────────────────────────────────────────────────
        high_count = sum(1 for c in result.clauses if any(f.get("severity") == "high" for f in c.rule_flags) or c.learned_severity == "high")
        med_count  = sum(1 for c in result.clauses if any(f.get("severity") == "medium" for f in c.rule_flags) or c.learned_severity == "medium")
        low_count  = sum(1 for c in result.clauses if any(f.get("severity") == "low" for f in c.rule_flags) or c.learned_severity == "low")
        miss_count = len(result.missing_categories)

        m1, m2, m3, m4 = st.columns(4)
        m1.metric("HIGH Priority", high_count, delta=None)
        m2.metric("MEDIUM Priority", med_count, delta=None)
        m3.metric("LOW Priority", low_count, delta=None)
        m4.metric("Missing Provisions", miss_count, delta=None)

        st.markdown("<br>", unsafe_allow_html=True)

        # ── Full report ──────────────────────────────────────────────────────
        st.markdown('<div class="glass-card">', unsafe_allow_html=True)
        st.markdown(review_report)
        st.markdown('</div>', unsafe_allow_html=True)

        # ── Download PDF ──────────────────────────────────────────────────────
        st.markdown("<br>", unsafe_allow_html=True)
        from services.pdf_generator import create_pdf
        
        pdf_bytes = create_pdf(
            contract_text=review_report,
            contract_title=f"Contract Review — {contract_name}",
            contract_type="Contract Review Report",
        )

        if not pdf_bytes.startswith(b"%PDF"):
            st.error("PDF generation failed: generated content is not a valid PDF.")
        else:
            safe_filename = contract_name.replace(" ", "_").replace("/", "_")
            if safe_filename.endswith(".pdf") or safe_filename.endswith(".docx"):
                safe_filename = safe_filename.rsplit(".", 1)[0]
            st.download_button(
                label="📄 Download Contract Review PDF",
                data=pdf_bytes,
                file_name=f"contract_review_report_{safe_filename}.pdf",
                mime="application/pdf",
                use_container_width=True,
            )